secrets:
  create: true
  userTradesPgCon: ""
  hedgingPgCon: ""
  okexSecretKey: ""
  okexPassphrase: ""
  galoyPhoneCode: ""
stablesats:
  image:
    repository: us.gcr.io/galoy-org/stablesats-rs
    digest: "sha256:b468f0318fe1bc9f347550455035ae8875ef3f47cdc14d294014c78fecbda958"
    git_ref: "482feb1"
  crash_report_config_danger: false
  userTrades:
    enabled: true
    balancePublishFrequency: 5
    galoyPollFrequency: 5
  hedging:
    enabled: true
    okexPollFrequency: 10
  priceServer:
    port: 3325
    fees:
      baseFeeRate: 0.0008
      immediateFeeRate: 0.0005
      delayedFeeRate: 0.0007
  galoy:
    api: "https://api.staging.galoy.io/graphql"
    phoneNumber: "+50365055530"
  okex:
    apiKey: ""
    simulated: true
  tracing:
    jaegerHost: "localhost"
    serviceName: "stablesats"
redis:
  enabled: true
  master:
    persistence:
      enabled: true
  auth:
    password: password
  sentinel:
    enabled: true
  metrics:
    enabled: true
user-trades-pg:
  enabled: true
  auth:
    enablePostgresUser: false
    username: stablesats
    password: stablesats
    database: stablesats-user-trades
hedging-pg:
  enabled: true
  auth:
    enablePostgresUser: false
    username: stablesats
    password: stablesats
    database: stablesats-hedging
