apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dealer.fullname" . }}
  labels:
    app: {{ template "dealer.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  selector:
    matchLabels:
      app: {{ template "dealer.fullname" . }}
      release: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "dealer.fullname" . }}
        release: "{{ .Release.Name }}"
      annotations:
        prometheus.io/path: {{ .Values.dealer.exporter.path }}
        prometheus.io/port: "{{ .Values.dealer.exporter.port }}"
        prometheus.io/scrape: "true"
      {{- with .Values.dealer.annotations }}
        {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.dealer.image.repository }}@{{ .Values.dealer.image.digest }}"
        args:
        - "-r"
        - "/app/dealer/lib/services/tracing.js"
        - "/app/dealer/lib/app/start.js"
        volumeMounts:
        - name: "custom-yaml"
          mountPath: "/var/yaml/"
        env:
        - name: NETWORK
          value: {{ .Values.dealer.network }}
        - name: JAEGER_HOST
          value: {{ $.Values.jaegerHost }}
        - name: TRACING_SERVICE_NAME
          value: "{{ $.Values.tracingPrefix }}-dealer"
        - name: LOG_LEVEL
          value: {{ .Values.dealer.logLevel }}
        - name: ACTIVE_STRATEGY
          value: {{ .Values.dealer.activeStrategy }}
        - name: ACTIVE_WALLET
          value: {{ .Values.dealer.activeWallet }}
        - name: HEDGING_DISABLED
          value: "{{ .Values.dealer.hedgingIsDisabled }}"
        - name: HEDGING_NOT_IN_SIMULATION
          value: "{{ .Values.dealer.hedgingNotInSimulation }}"
        - name: OKEX5_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.dealer.okex5.secretName }}
              key: {{ .Values.dealer.okex5.secretKey.key }}
        - name: OKEX5_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.dealer.okex5.secretName }}
              key: {{ .Values.dealer.okex5.secretKey.secret }}
        - name: OKEX5_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.dealer.okex5.secretName }}
              key: {{ .Values.dealer.okex5.secretKey.password }}
        - name: OKEX5_FUND_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.dealer.okex5.secretName }}
              key: {{ .Values.dealer.okex5.secretKey.fundPassword }}
        - name: GRAPHQL_URI
          value: {{ .Values.dealer.graphqlUri }}
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.dealer.databaseUrl.secretName }}
              key: {{ .Values.dealer.databaseUrl.secretKey }}
        - name: DEALER_PHONE
          valueFrom:
            secretKeyRef:
              name: dealer-creds
              key: phone
        - name: DEALER_CODE
          valueFrom:
            secretKeyRef:
              name: dealer-creds
              key: code
        resources:
          {{ toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: "custom-yaml"
        secret:
          secretName: "dealer-config-map"
