image:
  repository: us.gcr.io/galoy-org/web-wallet
  digest: "sha256:9422b46360f1fcd985eaf81908dc7e9df84f120906b8851082ceee47b23f4eb2"
  git_ref: "e61e91c" # Not used by helm
mobileLayout:
  enabled: false
  image:
    repository: us.gcr.io/galoy-org/web-wallet-mobile-layout
    digest: "sha256:9422b46360f1fcd985eaf81908dc7e9df84f120906b8851082ceee47b23f4eb2"
ingress:
  enabled: false
service:
  port: 80
  type: ClusterIP
webWallet:
  jaegerHost: localhost
  tracingPrefix: "galoy"
  bitcoinNetwork: regtest
  authEndpoint: api/login
  graphqlUrl: http://localhost:4002/graphql
  graphqlSubscriptionUrl: wss://localhost:4002/graphql
  supportEmail: support@galoy.io
  walletName: galoy
  galoyPayEndpoint: http://localhost:4000
  galoyAuthEndpoint: http://localhost:4001/auth/browser
  kratos:
    enabled: false
    browserUrl: http://localhost:4433
    apiUrl: http://localhost:4433
secrets:
  ## Create the secret resource from the following values. Set this to
  ## false to manage these secrets outside Helm.
  ## Checkout templates/secrets.yaml to get the appropriate template
  ## Set this to true and set secrets.sessionKeys to the
  ## value of the session key to have a secret be created
  create: false
  ## cookieSession keys
  sessionKeys: "session-keys"
