apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ template "galoy.admin.fullname" . }}
  labels:
    app: {{ template "galoy.admin.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: Helm

    kube-monkey/enabled: enabled
    kube-monkey/identifier: {{ template "galoy.admin.fullname" . }}
    kube-monkey/kill-mode: fixed
    kube-monkey/kill-value: "1"
    kube-monkey/mtbf: "8"

spec:

  replicas: {{ .Values.galoy.admin.replicas }}

  selector:
    matchLabels:
      app: {{ template "galoy.admin.fullname" . }}

  template:

    metadata:
      name: {{ template "galoy.admin.fullname" . }}
      labels:
        app: {{ template "galoy.admin.fullname" . }}
        kube-monkey/enabled: enabled
        kube-monkey/identifier: {{ template "galoy.admin.fullname" . }}
        allow-to-lnd: "true"
        allow-to-bitcoind: "true"

    spec:
      serviceAccountName: {{ template "galoy.name" . }}

      initContainers:
      - name: wait-for-mongodb-migrate
        image: "groundnuty/k8s-wait-for:v1.5.1"
        args:
        - job-wr
        - {{ template "galoy.migration.jobname" . }}

      containers:
      - name: admin
        image: "{{ .Values.galoy.images.app.repository }}@{{ .Values.galoy.images.app.digest }}"
        args:
        - "-r"
        - "/app/lib/services/tracing.js"
        - "lib/servers/graphql-admin-server.js"

        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 1000m

        ports:
        - name: http
          containerPort: {{ .Values.galoy.admin.port }}
          protocol: TCP

        env:
        - name: HELMREVISION
          value: {{ .Release.Revision | quote}}
        - name: NODE_ENV
          value: "production"
        - name: LOGLEVEL
          value: {{ .Values.galoy.admin.logLevel | quote }}

        - name: NETWORK
          value: {{ .Values.galoy.network }}
        - name: GALOY_ADMIN_PORT
          value: {{ .Values.galoy.admin.port | quote }}

        - name: JAEGER_HOST
          value: {{ .Values.tracing.jaegerHost | quote }}
        - name: TRACING_SERVICE_NAME
          value: "{{ .Values.tracing.prefix }}-{{ template "galoy.admin.fullname" . }}"

{{/* Databases */}}
{{ include "galoy.mongodb.env" . | indent 8 }}
{{ include "galoy.redis.env" . | indent 8 }}

{{/* Bitcoin/LND */}}
{{ include "galoy.bitcoind.env" . | indent 8 }}
{{ include "galoy.lnd1.env" . | indent 8 }}
{{ include "galoy.lnd2.env" . | indent 8 }}

{{/* API Specifics */}}
{{ include "galoy.twilio.env" . | indent 8 }}
{{ include "galoy.geetest.env" . | indent 8 }}
{{ include "galoy.jwt.env" . | indent 8 }}

        - name: KRATOS_MASTER_PHONE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.galoy.kratos.existingSecret.name }}
              key: {{ .Values.galoy.kratos.existingSecret.password }}
        - name: KRATOS_CALLBACK_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.galoy.kratos.existingSecret.name }}
              key: {{ .Values.galoy.kratos.existingSecret.api_key }}

        - name: PRICE_HISTORY_HOST
          value: {{ .Values.price.host | quote }}
        - name: PRICE_HISTORY_PORT
          value: {{ .Values.price.port | quote }}

        - name: PRICE_SERVER_HOST
          value: {{ .Values.galoy.dealer.host | quote }}
        - name: PRICE_SERVER_PORT
          value: {{ .Values.galoy.dealer.port | quote }}

        {{ if .Values.galoy.admin.probes.enabled }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.galoy.admin.port }}
          initialDelaySeconds: {{ .Values.galoy.admin.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.galoy.admin.probes.liveness.periodSeconds }}
          failureThreshold: {{ .Values.galoy.admin.probes.liveness.failureThreshold }}
          timeoutSeconds: {{ .Values.galoy.admin.probes.liveness.timeoutSeconds }}

        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.galoy.admin.port }}
          initialDelaySeconds: {{ .Values.galoy.admin.probes.readiness.initialDelaySeconds }}
          failureThreshold: {{ .Values.galoy.admin.probes.readiness.failureThreshold }}
          successThreshold: {{ .Values.galoy.admin.probes.readiness.successThreshold }}
          timeoutSeconds: {{ .Values.galoy.admin.probes.readiness.timeoutSeconds }}
        {{ end }}

        volumeMounts:
        - name: custom-yaml
          mountPath: "/var/yaml/"

      volumes:
      - name: custom-yaml
        secret:
          secretName: "{{ template "galoy.config.name" . }}"
