apiVersion: v2
name: lnd
version: 0.4.13-dev
appVersion: 0.16.1
description: LND helm chart
keywords:
  - lnd
maintainers:
  - name: krtk6160
    email: krtk6160@galoy.io
  - name: nicolasburtey
    email: nb@galoy.io
engine: gotpl
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 2.4.0
